stages:
  - sast

sast-scans:
  stage: sast
  image: maven:3.8.8-eclipse-temurin-11
  script:
    - mvn clean install
    - mvn org.cyclonedx:cyclonedx-maven-plugin:2.7.9:makeAggregateBom
  artifacts:
    paths:
      - target/bom.json
    name: sbom-cyclonedx.json